[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
lib_deps = 
	knolleary/PubSubClient @ ^2.8
	bblanchon/ArduinoJson @ ^6.21.3
	adafruit/DHT sensor library @ ^1.4.6
	adafruit/Adafruit Unified Sensor @ ^1.1.14
	adafruit/Adafruit BME280 Library @ ^2.2.4

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
lib_deps = 
	${env:nodemcuv2.lib_deps}
